port: 8741
base_url: /
youtube_api_key: "<PUT YOUR KEY HERE>"

# Optional, if you want to activate the anime part of the website:
anime: 
  enable: false
  mal_client_id: null

# If you want to get sms notifications when retrieval fails
sms_notifs: 
  enable: false
  id: null
  password: null

users: 
  enable: false

# Some configuration relative to password storage
passwords: 
  # Number of rounds of the bcrypt algorithm to run for password hashing
  bcrypt_rounds: 12
  # Can be set to true (only https), false, or 'auto' (adapts to connection types)
  secure_cookies: 'auto'
  # This value is used to sign the session cookies (preventing users from forging
  # fakes).
  cookies_secret: "PUT_SECRET_HERE"